# Generated by Django 3.0.4 on 2020-05-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200515_0755'),
        ('accounts', '0003_auto_20200513_1204'),
    ]

    operations = [
    ]
