# Generated by Django 3.0.4 on 2020-04-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200418_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', height_field=500, upload_to='profile_pics', width_field=500),
        ),
    ]
