# Generated by Django 3.0.3 on 2020-05-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200426_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
