# Generated by Django 3.0.5 on 2020-04-22 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('what_student_will_learn', models.TextField()),
                ('description', models.TextField()),
                ('prerequisite', models.TextField()),
                ('who_this_course_is_for', models.TextField()),
                ('type', models.CharField(choices=[('video/audio', 'Video/Audio'), ('pdf', 'pdf'), ('ebook', 'ebook')], max_length=100)),
                ('no_of_content', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Tutorial')),
            ],
        ),
        migrations.CreateModel(
            name='TutorialContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video_url', models.CharField(default=None, max_length=255)),
                ('file1', models.CharField(default=None, max_length=255)),
                ('file2', models.CharField(default=None, max_length=255)),
                ('file3', models.CharField(default=None, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('objective', models.TextField()),
                ('description', models.TextField()),
                ('payment_conformation', models.PositiveSmallIntegerField(default=1)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Tutorial')),
            ],
        ),
    ]
