# Generated by Django 3.0.5 on 2020-05-09 18:02

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('what_student_will_learn', models.TextField(blank=True, help_text='What Student will learn', null=True)),
                ('description', models.TextField()),
                ('prerequisite', models.TextField(blank=True, help_text='What Student Should Learn Before Enrolling to this Course', null=True)),
                ('who_this_course_is_for', models.TextField(blank=True, help_text='Who this course can target', null=True)),
                ('no_of_content', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of course on Dollars', max_digits=6)),
                ('thumbnail', models.ImageField(upload_to='course')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Category')),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Category')),
            ],
            options={
                'verbose_name_plural': 'SubCategory',
            },
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Eposide', max_length=255)),
                ('video_url', embed_video.fields.EmbedVideoField(help_text='Enter the Video url of youtube or vimeo')),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('objective', models.TextField(blank=True, null=True)),
                ('description', models.TextField(help_text='Detail about this Eposide')),
                ('payment_confirmation', models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'verbose_name_plural': 'Course Insight',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.SubCategory'),
        ),
    ]
