# Generated by Django 3.0.5 on 2020-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200422_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorialcontent',
            name='file1',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tutorialcontent',
            name='file2',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tutorialcontent',
            name='file3',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='tutorialcontent',
            name='payment_conformation',
            field=models.CharField(choices=[(1, 'Yes'), (2, 'No')], max_length=100),
        ),
    ]
