# Generated by Django 3.0.5 on 2020-04-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200422_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcontent',
            name='payment_conformation',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=100),
        ),
    ]
