# Generated by Django 3.0.6 on 2020-05-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_enroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='user_id',
            new_name='user',
        ),
    ]
