# Generated by Django 3.0.5 on 2020-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200422_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcontent',
            name='payment_conformation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (0, 'No')]),
        ),
    ]
