# Generated by Django 3.0.5 on 2020-04-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200422_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcontent',
            name='file1',
            field=models.FileField(default='', upload_to='course/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorialcontent',
            name='file2',
            field=models.FileField(default='', upload_to='course/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tutorialcontent',
            name='file3',
            field=models.FileField(default='', upload_to='course/uploads/%Y/%m/%d/'),
        ),
    ]
