# Generated by Django 3.0.5 on 2020-04-22 22:17

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200422_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcontent',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
