# Generated by Django 3.0.3 on 2020-04-26 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0008_auto_20200422_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tutorialcontent',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='tutorialcontent',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='tutorialcontent',
            name='file3',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
            preserve_default=False,
        ),
    ]
