# Generated by Django 3.0.3 on 2020-04-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_tutorial_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='status',
        ),
    ]
