# Generated by Django 3.0.3 on 2020-04-30 05:42

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_tutorial_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video_url', embed_video.fields.EmbedVideoField()),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('objective', models.TextField()),
                ('description', models.TextField()),
                ('payment_conformation', models.PositiveSmallIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorialtag',
            name='tutorial',
        ),
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='Course',
        ),
        migrations.DeleteModel(
            name='TutorialContent',
        ),
        migrations.DeleteModel(
            name='TutorialTag',
        ),
        migrations.AddField(
            model_name='coursetag',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
