# Generated by Django 3.0.3 on 2020-04-30 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20200430_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontent',
            old_name='payment_conformation',
            new_name='payment_confirmation',
        ),
    ]
