# Generated by Django 3.0.3 on 2020-04-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20200430_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='what_student_will_learn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='who_this_course_is_for',
            field=models.TextField(null=True),
        ),
    ]
