# Generated by Django 3.0.3 on 2020-04-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20200430_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
