# Generated by Django 3.0.3 on 2020-04-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20200430_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.TextField(blank=True, help_text='What Student Should Learn Before Enrolling to this Course', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of course on Dollars', max_digits=6),
        ),
    ]
