# Generated by Django 3.0.3 on 2020-04-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_auto_20200430_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='course'),
            preserve_default=False,
        ),
    ]
