# Generated by Django 3.0.3 on 2020-04-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_course_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecontent',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursetag',
            old_name='Course',
            new_name='course',
        ),
    ]
